/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Text;
export const Timestamp = IDL.Int;
export const Expense = IDL.Record({
  'id' : UserId,
  'userId' : IDL.Text,
  'date' : Timestamp,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'amount' : IDL.Float64,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'age' : IDL.Nat,
  'principal' : IDL.Principal,
  'primaryGoal' : IDL.Text,
  'debtAmount' : IDL.Float64,
  'familyResponsibility' : IDL.Text,
  'isPremium' : IDL.Bool,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'gender' : IDL.Opt(IDL.Text),
  'careerInterest' : IDL.Text,
  'businessInterest' : IDL.Text,
  'currentSavings' : IDL.Float64,
  'currentStudy' : IDL.Text,
  'skills' : IDL.Vec(IDL.Text),
  'educationLevel' : IDL.Text,
  'riskLevel' : IDL.Text,
  'monthlyExpenses' : IDL.Float64,
  'monthlyIncome' : IDL.Float64,
});
export const SavingsPlan = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'dailyTarget' : IDL.Float64,
  'userId' : IDL.Text,
  'emergencyFundCurrent' : IDL.Float64,
  'habits' : IDL.Vec(IDL.Text),
  'emergencyFundTarget' : IDL.Float64,
  'monthlyTarget' : IDL.Float64,
  'debtPlan' : IDL.Text,
  'weeklyTarget' : IDL.Float64,
});
export const AIReport = IDL.Record({
  'suggestions' : IDL.Vec(IDL.Text),
  'userId' : IDL.Text,
  'generatedAt' : Timestamp,
  'budgetBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
});
export const AdminStats = IDL.Record({
  'popularBusinessIdeas' : IDL.Vec(IDL.Text),
  'premiumUsers' : IDL.Nat,
  'popularCareers' : IDL.Vec(IDL.Text),
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Float64,
});
export const DailyTask = IDL.Record({
  'id' : UserId,
  'userId' : IDL.Text,
  'date' : Timestamp,
  'text' : IDL.Text,
  'completed' : IDL.Bool,
});
export const PremiumSubscription = IDL.Record({
  'status' : IDL.Text,
  'userId' : IDL.Text,
  'plan' : IDL.Text,
  'currentPeriodEnd' : Timestamp,
  'stripeCustomerId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addExpense' : IDL.Func([Expense], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [UserProfile], []),
  'deleteExpense' : IDL.Func([IDL.Text], [], []),
  'generateSavingsPlan' : IDL.Func([], [SavingsPlan], []),
  'getAIReport' : IDL.Func([], [IDL.Opt(AIReport)], ['query']),
  'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyTasks' : IDL.Func([], [IDL.Vec(DailyTask)], ['query']),
  'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
  'getMySubscription' : IDL.Func([], [IDL.Opt(PremiumSubscription)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getSavingsPlan' : IDL.Func([], [IDL.Opt(SavingsPlan)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAIReport' : IDL.Func([AIReport], [], []),
  'updatePremiumStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateSavingsPlan' : IDL.Func([SavingsPlan], [], []),
  'updateTaskCompletion' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'upsertSubscription' : IDL.Func([PremiumSubscription], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Text;
  const Timestamp = IDL.Int;
  const Expense = IDL.Record({
    'id' : UserId,
    'userId' : IDL.Text,
    'date' : Timestamp,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'age' : IDL.Nat,
    'principal' : IDL.Principal,
    'primaryGoal' : IDL.Text,
    'debtAmount' : IDL.Float64,
    'familyResponsibility' : IDL.Text,
    'isPremium' : IDL.Bool,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'gender' : IDL.Opt(IDL.Text),
    'careerInterest' : IDL.Text,
    'businessInterest' : IDL.Text,
    'currentSavings' : IDL.Float64,
    'currentStudy' : IDL.Text,
    'skills' : IDL.Vec(IDL.Text),
    'educationLevel' : IDL.Text,
    'riskLevel' : IDL.Text,
    'monthlyExpenses' : IDL.Float64,
    'monthlyIncome' : IDL.Float64,
  });
  const SavingsPlan = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'dailyTarget' : IDL.Float64,
    'userId' : IDL.Text,
    'emergencyFundCurrent' : IDL.Float64,
    'habits' : IDL.Vec(IDL.Text),
    'emergencyFundTarget' : IDL.Float64,
    'monthlyTarget' : IDL.Float64,
    'debtPlan' : IDL.Text,
    'weeklyTarget' : IDL.Float64,
  });
  const AIReport = IDL.Record({
    'suggestions' : IDL.Vec(IDL.Text),
    'userId' : IDL.Text,
    'generatedAt' : Timestamp,
    'budgetBreakdown' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Float64)),
  });
  const AdminStats = IDL.Record({
    'popularBusinessIdeas' : IDL.Vec(IDL.Text),
    'premiumUsers' : IDL.Nat,
    'popularCareers' : IDL.Vec(IDL.Text),
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Float64,
  });
  const DailyTask = IDL.Record({
    'id' : UserId,
    'userId' : IDL.Text,
    'date' : Timestamp,
    'text' : IDL.Text,
    'completed' : IDL.Bool,
  });
  const PremiumSubscription = IDL.Record({
    'status' : IDL.Text,
    'userId' : IDL.Text,
    'plan' : IDL.Text,
    'currentPeriodEnd' : Timestamp,
    'stripeCustomerId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addExpense' : IDL.Func([Expense], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [UserProfile], []),
    'deleteExpense' : IDL.Func([IDL.Text], [], []),
    'generateSavingsPlan' : IDL.Func([], [SavingsPlan], []),
    'getAIReport' : IDL.Func([], [IDL.Opt(AIReport)], ['query']),
    'getAdminStats' : IDL.Func([], [AdminStats], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyTasks' : IDL.Func([], [IDL.Vec(DailyTask)], ['query']),
    'getExpenses' : IDL.Func([], [IDL.Vec(Expense)], ['query']),
    'getMySubscription' : IDL.Func(
        [],
        [IDL.Opt(PremiumSubscription)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getSavingsPlan' : IDL.Func([], [IDL.Opt(SavingsPlan)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAIReport' : IDL.Func([AIReport], [], []),
    'updatePremiumStatus' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateSavingsPlan' : IDL.Func([SavingsPlan], [], []),
    'updateTaskCompletion' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'upsertSubscription' : IDL.Func([PremiumSubscription], [], []),
  });
};

export const init = ({ IDL }) => { return []; };