/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIReport {
  'suggestions' : Array<string>,
  'userId' : string,
  'generatedAt' : Timestamp,
  'budgetBreakdown' : Array<[string, number]>,
}
export interface AdminStats {
  'popularBusinessIdeas' : Array<string>,
  'premiumUsers' : bigint,
  'popularCareers' : Array<string>,
  'totalUsers' : bigint,
  'totalRevenue' : number,
}
export interface DailyTask {
  'id' : UserId,
  'userId' : string,
  'date' : Timestamp,
  'text' : string,
  'completed' : boolean,
}
export interface Expense {
  'id' : UserId,
  'userId' : string,
  'date' : Timestamp,
  'description' : string,
  'category' : string,
  'amount' : number,
}
export interface PremiumSubscription {
  'status' : string,
  'userId' : string,
  'plan' : string,
  'currentPeriodEnd' : Timestamp,
  'stripeCustomerId' : string,
}
export interface SavingsPlan {
  'suggestions' : Array<string>,
  'dailyTarget' : number,
  'userId' : string,
  'emergencyFundCurrent' : number,
  'habits' : Array<string>,
  'emergencyFundTarget' : number,
  'monthlyTarget' : number,
  'debtPlan' : string,
  'weeklyTarget' : number,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'age' : bigint,
  'principal' : Principal,
  'primaryGoal' : string,
  'debtAmount' : number,
  'familyResponsibility' : string,
  'isPremium' : boolean,
  'city' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'gender' : [] | [string],
  'careerInterest' : string,
  'businessInterest' : string,
  'currentSavings' : number,
  'currentStudy' : string,
  'skills' : Array<string>,
  'educationLevel' : string,
  'riskLevel' : string,
  'monthlyExpenses' : number,
  'monthlyIncome' : number,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addExpense' : ActorMethod<[Expense], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], UserProfile>,
  'deleteExpense' : ActorMethod<[string], undefined>,
  'generateSavingsPlan' : ActorMethod<[], SavingsPlan>,
  'getAIReport' : ActorMethod<[], [] | [AIReport]>,
  'getAdminStats' : ActorMethod<[], AdminStats>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyTasks' : ActorMethod<[], Array<DailyTask>>,
  'getExpenses' : ActorMethod<[], Array<Expense>>,
  'getMySubscription' : ActorMethod<[], [] | [PremiumSubscription]>,
  'getProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getSavingsPlan' : ActorMethod<[], [] | [SavingsPlan]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAIReport' : ActorMethod<[AIReport], undefined>,
  'updatePremiumStatus' : ActorMethod<[string, boolean], undefined>,
  'updateSavingsPlan' : ActorMethod<[SavingsPlan], undefined>,
  'updateTaskCompletion' : ActorMethod<[string, boolean], undefined>,
  'upsertSubscription' : ActorMethod<[PremiumSubscription], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];